---
# Crazyflie 0
- ros_topic_name: "/crazyflie0/cmd_vel"
  gz_topic_name: "/model/crazyflie0/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/crazyflie0/odom"
  gz_topic_name: "/model/crazyflie0/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie0/scan"
  gz_topic_name: "/model/crazyflie0/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie0/tf"
  gz_topic_name: "/model/crazyflie0/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Crazyflie 1
- ros_topic_name: "/crazyflie1/cmd_vel"
  gz_topic_name: "/model/crazyflie1/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/crazyflie1/odom"
  gz_topic_name: "/model/crazyflie1/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie1/scan"
  gz_topic_name: "/model/crazyflie1/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie1/tf"
  gz_topic_name: "/model/crazyflie1/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Crazyflie 2
- ros_topic_name: "/crazyflie2/cmd_vel"
  gz_topic_name: "/model/crazyflie2/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/crazyflie2/odom"
  gz_topic_name: "/model/crazyflie2/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie2/scan"
  gz_topic_name: "/model/crazyflie2/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie2/tf"
  gz_topic_name: "/model/crazyflie2/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Crazyflie 3
- ros_topic_name: "/crazyflie3/cmd_vel"
  gz_topic_name: "/model/crazyflie3/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/crazyflie3/odom"
  gz_topic_name: "/model/crazyflie3/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie3/scan"
  gz_topic_name: "/model/crazyflie3/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie3/tf"
  gz_topic_name: "/model/crazyflie3/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Crazyflie 4
- ros_topic_name: "/crazyflie4/cmd_vel"
  gz_topic_name: "/model/crazyflie4/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/crazyflie4/odom"
  gz_topic_name: "/model/crazyflie4/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie4/scan"
  gz_topic_name: "/model/crazyflie4/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/crazyflie4/tf"
  gz_topic_name: "/model/crazyflie4/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Common topics
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
